export {default as Home} from './Home/Home';
export {default as Search} from './Search/Search';
export {default as Login} from './Login/Login';
export {default as SignUp} from './SignUp/SignUp';
// export {default as Settings} from './me/Me';
export {default as CreateProduct} from './CreateProduct/CreateProduct';
export {default as ProductDetails} from './ProductDetails/ProductDetails';
export {default as Cart} from './cart/Cart';
export {default as ShippingDetails} from './shippingDetails/ShippingDetails';
export {default as Confarm} from './confarm/Confarm.js';
export {default as Payment} from './payment/Payment';
export {default as SignOut} from './SignOut/SignOut';
export {default as Profile} from './me/Me';
export {default as Settings} from './Settings/Settings';
export {default as Myorder} from './Myorder/Myorder';
