export default {
  home: require('../assets/images/home.png'),
  account: require('../assets/images/account.png'),
  cart: require('../assets/images/cart.png'),
  add: require('../assets/images/add.png'),
  account: require('../assets/images/account.png'),
  dashboard: require('../assets/images/dashboard.png'),
  user: require('../assets/images/user.png'),
  email: require('../assets/images/email.png'),
  lock: require('../assets/images/lock.png'),
  facebook: require('../assets/images/facebook.png'),
  google: require('../assets/images/google.png'),
  search: require('../assets/images/search.png'),
  back: require('../assets/images/back.png'),
  bg: require('../assets/images/bg.jpg'),
  profile: require('../assets/images/profile.png'),
  cart1: require('../assets/images/cart1.png'),
  delete: require('../assets/images/delete.png'),
  drop_dawn: require('../assets/images/drop_dawn.png'),

  // dropdownTriangle: require('../assets/images/ic_dropdown.png'),
  // fb: require('../assets/images/ic_facebook.png'),
  // apple: require('../assets/images/ic_apple.png'),
  // google: require('../assets/images/ic_google.png'),
  // insta: require('../assets/images/ic_insta.png'),
  // back: require('../assets/images/ic_back.png'),
  // backWithSquare: require('../assets/images/backWithSquare.png'),
  // rightBlue: require('../assets/images/ic_goA.png'),
  // landingImage:require('../assets/images/landingImage.jpeg'),
  // landingImage1:require('../assets/images/landingImage1.jpeg'),
  // landingImage2:require('../assets/images/landingImage2.jpeg'),
  // loginchoiceImage:require('../assets/images/loginchoicengImage.jpg'),
  // shop:require('../assets/images/shop.png'),
  // chat:require('../assets/images/chat.png'),
  // heartPlush:require('../assets/images/heartPulsh.png'),
  // visit:require('../assets/images/visit.png'),
  // cart:require('../assets/images/cart.png'),
  // flash_sale:require('../assets/images/flash-icon.png'),
  // lock:require('../assets/images/lock.png'),
  // drawer_icon:require('../assets/images/drawer.png'),
  // search_icon:require('../assets/images/search.png'),
  // notification:require('../assets/images/notification.png'),
  // profile:require('../assets/images/profile.png'),
  // qrcode:require('../assets/images/qrcode.png'),
};
