export default {
  LOGIN: 'login',
  SIGN_UP: 'signUp',
  SIGN_OUT:"SignOut",
  HOME: 'home',
  HOME_STACK: 'homeStack',
  SEARCH: 'search',
  PRODUCT_INFO: 'ProductDetails',
  CART: 'cart',
  SHIPPING_INFO: 'shippingDetails',
  CREATE_PRODUCT: 'createProduct',
  CONFARM: 'confarm',
  PAYMENT_ORDER:"payment",
  PROFILE:"profile",
  SETINGS_STACK:"SetingsStack",
  SETTINGS:"settings",
  MY_ORDERS:"myorder",


  //dddddddddddddddddddd
  OTP_VERIFICATION: 'otpVerfication',
  OUTER_SCREEN: 'outerScreen',
  OFFERS: 'offers',
  BRANDS: 'brands',
  CELEBRITY: 'celebrity',
  ACCOUNTS: 'accounts',
  TAB_ROUTES: 'tabRoutes',
  DELIVERY: 'delivery',
  RESTAURANT: 'restaurent',
  SUPERMARKET: 'supermarket',
  SUPERMARKET_PRODUCTS_CATEGORY: 'supermarketProductsCategory',
  PRODUCT_LIST: 'productList',
  LANDINGPAGE: 'LandingPage',
  CARTPRODUCT: 'CartProduct',
  TAB_ROUTES: 'tabRoutes',
  CONSULT: 'CONSULT',
  WORKOUT: 'WORKOUT',
  VISIT: 'VISIT',
  PROFILE: 'PROFILE',
  DRAWER_ROUTES: 'drawerRoutes',
  CHART: 'Chart',
  CHAT_SCREEN: 'ChatScreen',
  QR_CODESCREEN: 'QrCodeScreen',
  CONVERSECTION_USERS_LIST: 'ConversectionUsersList',
};
